// There are now 112 breeds

const breeds = [
  "Abyssinian",
  "Aegean Cat",
  "Alaskan Snow Cat",
  "American Bobtail",
  "American Burmese",
  "American Curl",
  "American Keuda",
  "American Lynx",
  "American Ringtail",
  "American Shorthair",
  "American Wirehair",
  "Antipodean",
  "Apple (Round) head Siamese",
  "Asian Longhair",
  "Asian Shorthair",
  "Australian Mist",
  "Balinese",
  "Bengal",
  "Birman",
  "Bombay",
  "Box Ear",
  "Brazilian Shorthair",
  "Britanica",
  "British Shorthair",
  "Burmese",
  "Burmilla",
  "Calico",
  "Calinfornia Regular",
  "California Spangled",
  "Chantilly/Tiffany",
  "Chartreux",
  "Chausie",
  "Cherubim",
  "Chinese White",
  "Classicat",
  "Clippercat",
  "Colorpoint Longhair",
  "Colorpoint Shorthair",
  "Contemporary Burmese",
  "Cornish Rex",
  "Cymric",
  "Desert Lynx",
  "Devon Rex",
  "Doll (Open) Faced Persian",
  "Domestic Longhair",
  "Domestic Shorthair",
  "Donskoy",
  "Don Sphynx",
  "Dragon Li",
  "Egyptian Mau",
  "European Burmese",
  "European Shorthair",
  "Exotic",
  "Exotic Shorthair",
  "Feline",
  "Foreign Longhair",
  "Foreign Shorthair",
  "Geoffroy's Cat",
  "German Rex",
  "Havana",
  "Havana Brown",
  "Highland Lynx",
  "Himalayan",
  "Honeybear",
  "Japanese Bobtail",
  "Javanese",
  "Javanese",
  "Jungala",
  "Kalico",
  "Karel Bobtail",
  "Korat",
  "Kucing Malaysia",
  "Kuril Bobtail",
  "LaPerm",
  "Maine Coon",
  "Mandalay",
  "Manx",
  "Marbled Mist",
  "Mekong Bobtail",
  "Mexican",
  "Minskin",
  "Miracle",
  "Moggy",
  "Munchkin",
  "Nebelung",
  "Neva Masquerade",
  "New Cat",
  "Norwegian Forest Cat",
  "Ocicat",
  "Oriental",
  "Oriental Shorthair",
  "Persian",
  "Peterbald",
  "Pixie-Bob",
  "RagaMuffin",
  "Ragdoll",
  "Russian Black",
  "Russian Blue",
  "Russian Hairless",
  "Russian Shorthair",
  "Russian White",
  "Savannah",
  "Scottish Fold",
  "Scottish Fold Two",
  "Selkirk Rex",
  "Siamese",
  "Siberian",
  "Singapura",
  "Snowshoe",
  "Sokoke",
  "Somali",
  "Sphynx",
  "Sterling",
  "Tabby",
  "Templecat",
  "Tiffanie",
  "Tiffany/Chantilly",
  "Tonkinese",
  "Toyger",
  "Toyger2TheElectricBoogaloo",
  "Turkish",
  "Turkish Angora",
  "Turkish Van",
  "Van Kedi"
]

module.exports = {
  getBreeds: breeds
}
